[vars]
NODE_VERSION = "20"
YARN_VERSION = "1.22.19"
PNPM_VERSION = "7.30.2"
NPM_VERSION = "9.6.7"

[build]
command = "npm install && npm run build"
directory = "dist"

[pages]
productionBranch = "master"

[placement]
mode = "smart"
